=== ManuAv05/Lenguaje_De_Marcas/lenguaje de marcas/XSD/EJERCICIO1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="relacion">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="email" type="xs:string" maxOccurs="unbounded" />

                            <xs:element name="parentesco" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="tipo" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>

                        <xs:attribute name="sexo" type="xs:string" use="optional"/>
                        <xs:attribute name="carnet" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ManuAv05/Lenguaje_De_Marcas/lenguaje de marcas/XSD/EJERCICIO1.xml
<?xml version="1.0" encoding="UTF-8"?>
<relacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

xsi:noNamespaceSchemaLocation="EJERCICIO1.xsd"

>
   <persona sexo="hombre" carnet="A1111">
     <nombre>Luis Martin</nombre>
     <email>luis@hotmail.com</email>
     <parentesco tipo="Padre"/>
   </persona>
   <persona sexo="mujer" carnet="B2222">
     <nombre>Laura Martin</nombre>
     <email>laura@hotmail.com</email>
     <parentesco tipo="Hija"/>
   </persona>
   <persona carnet="C3333">
     <nombre>Raul Gonzalez</nombre>
     <email>raul@hotmail.com</email>
     <email>raulin@gmail.com</email>
   </persona>
</relacion>
